"""FAR 23 LOADS -- shared pure-calc package for the McMaster suite.

Phase 0 ships the engine-mount module (a port of ENGLOADS.BAS); later phases add
the other programs as ``farloads/modules/<name>.py`` files that register
themselves with :mod:`farloads.registry`.
"""

from .models import (
    AeroCoeffSet,
    AeroInput,
    AeroSurfaceInput,
    BodyLoadResult,
    BodyStationLoad,
    CgCase,
    ConcentratedWeight,
    ConditionResult,
    CriticalCondition,
    CriticalLoadSet,
    EngineInput,
    EngineLayout,
    EngineType,
    EngineWeightType,
    EnvelopeResult,
    FlightLoadsInput,
    FuselageMassInput,
    FuselageStation,
    GeometryInput,
    LayoutInput,
    LoadsResult,
    LoadValue,
    MachLimitInput,
    MassCase,
    MassItem,
    MassItemKind,
    MassResult,
    ModuleResult,
    Project,
    Rotor,
    RotorDirection,
    RotorType,
    SCHEMA_VERSION,
    SelectInput,
    StructuralSpeedsInput,
    SurfaceInput,
    TailBalanceLoad,
    TailLoadsInput,
    VnPoint,
    VTailLoadsInput,
    WeightEnvelopeInput,
    WeightEstimationInput,
    WeightInput,
    WingLoadCase,
    WingLoadResult,
    WingMassInput,
    WingStationLoad,
)
from .units import (
    UnitSystem,
    convert_results,
    labels_for,
    to_display,
    to_imperial,
    to_imperial_scalar,
)
from . import io, registry

# Importing the modules package registers every module (engine, ...) and exposes
# the engine module's direct ``run_all(EngineInput)`` helper for back-compat.
from . import modules  # noqa: F401  (side effect: module registration)
from .modules.engine import run_all

__all__ = [
    "AeroCoeffSet",
    "AeroInput",
    "AeroSurfaceInput",
    "BodyLoadResult",
    "BodyStationLoad",
    "CgCase",
    "ConcentratedWeight",
    "ConditionResult",
    "CriticalCondition",
    "CriticalLoadSet",
    "EngineInput",
    "EngineLayout",
    "EngineType",
    "EngineWeightType",
    "EnvelopeResult",
    "FlightLoadsInput",
    "FuselageMassInput",
    "FuselageStation",
    "GeometryInput",
    "LayoutInput",
    "LoadsResult",
    "LoadValue",
    "MachLimitInput",
    "MassCase",
    "MassItem",
    "MassItemKind",
    "MassResult",
    "ModuleResult",
    "Project",
    "Rotor",
    "RotorDirection",
    "RotorType",
    "SCHEMA_VERSION",
    "SelectInput",
    "StructuralSpeedsInput",
    "SurfaceInput",
    "TailBalanceLoad",
    "TailLoadsInput",
    "VTailLoadsInput",
    "VnPoint",
    "WeightEnvelopeInput",
    "WeightEstimationInput",
    "WeightInput",
    "WingLoadCase",
    "WingLoadResult",
    "WingMassInput",
    "WingStationLoad",
    "run_all",
    "UnitSystem",
    "convert_results",
    "labels_for",
    "to_display",
    "to_imperial",
    "to_imperial_scalar",
    "io",
    "registry",
]
