"""sloads -- shared pure-calc package for the McMaster suite.

Phase 0 ships the engine-mount module (a port of ENGLOADS.BAS); later phases add
the other programs as ``sloads/modules/<name>.py`` files that register
themselves with :mod:`sloads.registry`.
"""

from .models import (
    AeroCoeffSet,
    AeroCoefficientsInput,
    AeroInput,
    AeroSurfaceInput,
    AileronLoadsInput,
    BodyLoadResult,
    BodyStationLoad,
    AnalysisKind,
    CgCase,
    GROUND_CASE_ROLE_ORDER,
    GearCarrier,
    GroundCaseRole,
    ConcentratedWeight,
    ConditionResult,
    ControlSurfaceLoadResult,
    ControlSurfaceStation,
    CriticalCondition,
    CriticalLoadSet,
    EngineInput,
    EmpennageInput,
    EngineLayout,
    EngineType,
    EngineWeightType,
    EnvelopeResult,
    FlapLoadsInput,
    FlightLoadsInput,
    FuselageMassInput,
    FuselageMomentInput,
    FuselageOutline,
    FuselageSection,
    FuselageStation,
    GearReactionCase,
    GeometryInput,
    default_fuselage_outline,
    LandingGearGeometry,
    LandingGearInput,
    LandingInput,
    LayoutInput,
    LoadsResult,
    LoadValue,
    MachLimitInput,
    MassCase,
    MassItem,
    MassItemKind,
    MassResult,
    MissingInputError,
    ModuleResult,
    OneEngineOutInput,
    Project,
    Rotor,
    RotorDirection,
    RotorType,
    SCHEMA_VERSION,
    SelectInput,
    StructuralSpeedsInput,
    SurfaceInput,
    TabLoadsInput,
    TabSpec,
    TailBalanceLoad,
    TailLoadsInput,
    TailType,
    VdBasis,
    VnPoint,
    VTailLoadsInput,
    WeightEnvelopeInput,
    WeightEstimationInput,
    WeightInput,
    WingLoadCase,
    WingLoadResult,
    WingMassInput,
    WingStationLoad,
)
from .units import (
    UnitSystem,
    convert_results,
    labels_for,
    si_scalar_label,
    to_display,
    to_imperial,
    to_imperial_scalar,
    to_si_scalar,
)
from . import io, registry
from .applicability import Exceedance, far23_applicability
from .fleet import FleetPoint, FleetStats, Subject, fleet_stats
from .validation import ConsistencyWarning, consistency_warnings
from .vn_diagram import GustInputs, VnDiagram, VnTrace, build_vn_diagram, resolve_gust_inputs
from .aero_curves import (
    AeroCurves,
    ClosureResult,
    CurveTrace,
    OperatingPoints,
    build_aero_curves,
    curve_closure,
    operating_points,
)

# Importing the modules package registers every module (engine, ...) and exposes
# the engine module's direct ``run_all(EngineInput)`` helper for back-compat.
from . import modules  # noqa: F401  (side effect: module registration)
from .modules.engine import run_all

__all__ = [
    "AeroCoeffSet",
    "AeroCoefficientsInput",
    "Exceedance",
    "far23_applicability",
    "FleetPoint",
    "FleetStats",
    "Subject",
    "fleet_stats",
    "ConsistencyWarning",
    "consistency_warnings",
    "GustInputs",
    "VnDiagram",
    "VnTrace",
    "build_vn_diagram",
    "resolve_gust_inputs",
    "AeroCurves",
    "ClosureResult",
    "CurveTrace",
    "OperatingPoints",
    "build_aero_curves",
    "curve_closure",
    "operating_points",
    "AeroInput",
    "AeroSurfaceInput",
    "AileronLoadsInput",
    "BodyLoadResult",
    "BodyStationLoad",
    "AnalysisKind",
    "CgCase",
    "GROUND_CASE_ROLE_ORDER",
    "GearCarrier",
    "GroundCaseRole",
    "ConcentratedWeight",
    "ConditionResult",
    "ControlSurfaceLoadResult",
    "ControlSurfaceStation",
    "CriticalCondition",
    "CriticalLoadSet",
    "EmpennageInput",
    "EngineInput",
    "EngineLayout",
    "EngineType",
    "EngineWeightType",
    "EnvelopeResult",
    "FlapLoadsInput",
    "FlightLoadsInput",
    "FuselageMassInput",
    "FuselageMomentInput",
    "FuselageOutline",
    "FuselageSection",
    "FuselageStation",
    "GearReactionCase",
    "GeometryInput",
    "default_fuselage_outline",
    "LandingGearGeometry",
    "LandingGearInput",
    "LandingInput",
    "LayoutInput",
    "LoadsResult",
    "LoadValue",
    "MachLimitInput",
    "MassCase",
    "MassItem",
    "MassItemKind",
    "MassResult",
    "MissingInputError",
    "ModuleResult",
    "OneEngineOutInput",
    "Project",
    "Rotor",
    "RotorDirection",
    "RotorType",
    "SCHEMA_VERSION",
    "SelectInput",
    "StructuralSpeedsInput",
    "SurfaceInput",
    "TabLoadsInput",
    "TabSpec",
    "TailBalanceLoad",
    "TailLoadsInput",
    "TailType",
    "VdBasis",
    "VTailLoadsInput",
    "VnPoint",
    "WeightEnvelopeInput",
    "WeightEstimationInput",
    "WeightInput",
    "WingLoadCase",
    "WingLoadResult",
    "WingMassInput",
    "WingStationLoad",
    "run_all",
    "UnitSystem",
    "convert_results",
    "labels_for",
    "si_scalar_label",
    "to_display",
    "to_imperial",
    "to_imperial_scalar",
    "to_si_scalar",
    "io",
    "registry",
]
